import type { Metadata } from 'next'
import { Inter,Poppins } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import NavbarClient from '@/components/Navbar/NavbarClient'
import Footer from '@/components/Footer/Footer'
import Providers from '@/reactQuery/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "600", "500", "700", "900"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-poppins`}>
        <Providers>
        <NavbarClient/>
        {children}
        <Footer/>
        </Providers>
        </body>
    </html>
  )
}
